### ISSUE TITLE
Be able to use relative URLS in Widget html 

### ISSUE THREAD

**Issue by sonoman** [wix/angular-widget#10]
I'm starting the Host App in a directory of my web server, let's say "/hostApp", and then I have some Angular Micro Applications in apps/app1, apps/app2, apps/app3 under hostApp directory.
in the manifest, I reference the assets for each one of the apps like this:
html: "/apps/app1/views/index.html"
files: [ "/apps/app1/js/app.js", "/apps/app1/js/util.js" 
This files load fine when boostraping the application. The thing is that inside index.html I have a couple of ng-include directives on which src attribute is specified relative to the index.html's path, actually the same directory: "./summary.html". But after index.html is loaded, the ng-include returns 404 because it's looking for "/hostApp/summary.html". is there a way to configure the base URL for that widget ?

**Comment by shahata** [comment]
Yes. Good question. This is one of the reasons we allow to pass config functions through the manifest generator into the micro app. The way we handle this in our projects is that we pass a config function which adds a `$http` interceptor that fixes the requests for the micro app. Here is a simplified version of what goes on in our manifest generator:

```js
angular.module('myApp').config(function (widgetsProvider) {
  function templateUrlPrefixer(prefix) {
    return ['$httpProvider', function ($httpProvider) {
      $httpProvider.interceptors.push(function () {
        return {
          request: function (config) {
            if (config.url.match(/\.html$/)) {
              if (!config.cache || !config.cache.get || !config.cache.get(config.url)) {
                config.url = prefix + config.url;
              }
            }
            return config;
          }
        };
      });
    }];
  }

  widgetsProvider.setManifestGenerator(function () {
    return function (name) {
      var relativeUrl = calcRelativeUrl(name);

      return {
        module: name,
        config: [templateUrlPrefixer(relativeUrl)],
        html: relativeUrl + name + '.html',
        files: [
          relativeUrl + 'scripts/' + name + '.js',
          relativeUrl + 'styles/' +  name + '.css'
        ]
      };
    };
  });
});
```
We also have a similar `relative-src` directive that we use instead of `ng-src` so that relative url's for image tags inside the micro app will work correctly. I'll try to add this functionality into `angular-widget` sometime soon so that people will not need to repeat this pattern.

**Comment by sonoman** [comment]
I see.....so you pass the function as module in the config function and is injected when bootstraping the micro app....is that right ?

**Comment by sonoman** [comment]
Comment Close issue

**Comment by sonoman** [comment]
I tried your code but when it tries to bootstrap the widget it complains about $httpProvider not available:
"Error: [$injector:modulerr] Failed to instantiate module $httpProvider due to:
Error: [$injector:nomod] Module '$httpProvider' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument."

**Comment by sonoman** [comment]
Nevermind, it was my error. thanks !
