### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by jpcamara** [wix/angular-widget#17]
Hey there!

I'm involved in a project using this module, and I'm interested in your thoughts on how an Angular 2 transition is going to work. From my understanding, this project is pretty tied to how things are currently loaded and managed in the angular 1.x runtime. 
Are there any concerns that a transition to Angular 2 will be difficult/impossible, or is there a sense that those aspects of the internals will be similar enough that the process won't be too bad?

Any insight would be great!

**Comment by pixelfish22** [comment]
+1 on the questions from @jpcamara .

**Comment by k-graefenhain** [comment]
+1 from me. Also looking for a widget library for Angular2 / Angular4.
