### ISSUE TITLE
angular.module('app3').run(angular.noop)

### ISSUE THREAD

**Issue by Falci** [wix/angular-widget#18]
Not sure why [this line](https://github.com/wix/angular-widget/blob/master/app/app3-dev.html#L19) is necessary.

```
    <script>
      angular.module('app3').run(['$state', '$urlRouter', angular.noop]);
    </script>
```

Although I tried to remove and the application no longer works

**Comment by shahata** [comment]
because the way ui-router works means that $state and $urlRouter services must be instantiated immediately when the application starts
